version: 0.2

env:
  variables:
    DJANGO_SETTINGS_MODULE: gitblog.settings

phases:
  install:
#    runtime-versions:
#      python: 3.9
    commands:
      - apt-get update -y
      - apt-get install -y nodejs python3.9
      - node --version
      - npm --version
      - python --version
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python manage.py tailwind install
      - python manage.py tailwind build
      - python manage.py collectstatic --noinput
      - npm install --location=global serverless
      - serverless plugin install --name=serverless-python-requirements
      - serverless plugin install --name=serverless-wsgi
      - serverless plugin install --name=serverless-domain-manager
      - serverless deploy
#  build:
#    commands:
#
  post_build:
    commands:
      - echo Build completed on `date`