# Generated by Django 4.0.6 on 2022-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_category_unique_blog_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
