# Generated by Django 4.0.6 on 2022-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
