# Generated by Django 4.0.6 on 2022-09-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
