# Generated by Django 4.0.6 on 2022-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
