# Generated by Django 4.0.6 on 2022-08-03 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubtoken',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='githubtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
